// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPElectronDemo.Data;

namespace TPElectronDemo.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20201202123355_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TPElectronDemo.Data.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4d7fcf3-1753-4196-a112-1bb48ab0bce7"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("1d6df14d-704e-4ea3-85fe-a0f82766a9c1"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("ceb73e5f-1f45-4033-9c05-54b491a4d9b1"),
                            Name = "Great Britain"
                        },
                        new
                        {
                            Id = new Guid("87caab56-eac1-45b5-8a2b-f13adc507e56"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("b8d232ea-38a1-4c6e-9a48-b6ff5994abdf"),
                            Name = "Italy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
